# Generated by Django 2.1.5 on 2020-04-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
