# Generated by Django 2.1.5 on 2020-04-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courceapp', '0003_auto_20200408_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
